package tdproto

// Push device info
type PushDevice struct {
	// Type: android, ios, web, safari
	Type string `json:"type"`

	// Device id generated by client library
	DeviceId string `json:"device_id"`

	// Notification token
	NotificationToken string `json:"notification_token"`

	// Notification token for VOIP (iOS only)
	VoipNotificationToken string `json:"voip_notification_token"`

	// Readable device name
	Name string `json:"name"`

	// Send silently data pushes that must be fully processed by app. Must be true for modern mobile clients
	DataPushes bool `json:"data_pushes"`

	// Send badge value as data. Experimental
	DataBadges bool `json:"data_badges"`

	// deprecated
	AllowedNotifications bool `json:"allowed_notifications"`
}
