package main

import (
	"fmt"
	"os"

	"github.com/tada-team/tdproto/inspect"
)

func main() {
	if err := inspect.Render(os.Stdout, `// Autogenerated. Do not edit.

type MessageLinks = MessageLink[];  {{- range $s := .Structs}}
/**
 * {{$s.Help}}.
 */
export interface {{$s.Name}} { {{- range $f := $s.Fields }}
   /**
    * {{$f.Help}}.{{ if $f.Omitempty }} Omitempty.{{ end }}
    */
   {{$f.JSName}}: {{$f.TSType}}{{ if $f.List }}[]{{end}}{{ if $f.Null }} | null{{ end }};
{{end}}
}

let New{{$s.Name}} = function(e: any): {{$s.Name}} { return {
	{{- range $i, $f := $s.Fields -}}
		{{- if (gt $i 0) }}, {{ end -}}
		{{- if $f.InternalType -}}
			{{- if $f.List -}}
				{{$f.JSName}}: e["{{$f.Json}}"].map(New{{ $f.TSType }})
			{{- else -}}
				{{$f.JSName}}: New{{ $f.TSType }}(e["{{$f.Json}}"])
			{{- end -}}
		{{- else -}}
	 		{{$f.JSName}}: e["{{$f.Json}}"]
        {{- end -}}
	{{- end -}}	
} }

{{end}}`); err != nil {
		fmt.Println(err)
	}
}
