package tdevents

func NewServerConfirm(v string) (r ServerConfirm) {
	r.Name = r.GetName()
	r.Params.ConfirmId = v
	return r
}

// Server confirmed client message
type ServerConfirm struct {
	BaseEvent
	Params serverConfirmParams `json:"params"`
}

func (p ServerConfirm) GetName() string { return "server.confirm" }

// Params of the server.confirm event
type serverConfirmParams struct {
	// Unique id generated by server
	ConfirmId string `json:"confirm_id"`
}
