---
name: Test swagger

on: workflow_dispatch

env:
  TDPROTO_DIR: tdproto
  CLONE_DIR: clone_dir
  OPENAPI_FILE: v4.json
  SWAGGER_VERSION: '3.47.1'
  SWAGGER_ARCHIVE: swagger.tar.gz

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: swagger_testing_deployment
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.TDPROTO_DIR }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Clone swagger page repo
        uses: actions/checkout@v2
        with:
          repository: 'tada-team/test-swagger'
          ssh-key: ${{ secrets.SWAGGER_DEPLOY_KEY }}
          path: ${{ env.CLONE_DIR }}
      - name: Clean swagger page repo
        continue-on-error: true
        working-directory: ${{ env.CLONE_DIR }}
        run: |
          rm $(git ls-files)
      - name: Get swagger release
        run: |
          SWAGGER_URL="https://github.com/swagger-api/swagger-ui/archive/refs/tags/v${SWAGGER_VERSION}.tar.gz"
          wget "$SWAGGER_URL" --output-document=${SWAGGER_ARCHIVE}
      - name: Prepare swagger files
        run: |
          SWAGGER_DIST_PATH="swagger-ui-${SWAGGER_VERSION}/dist"
          tar --extract --file "./swagger.tar.gz" "${SWAGGER_DIST_PATH}"
          mv "./${SWAGGER_DIST_PATH}/" "${CLONE_DIR}"
      - name: Modify swagger files
        working-directory: ${{ env.CLONE_DIR }}
        run: |
          mv "./dist/index.html" "./"
          sed --in-place 's/\.\//dist\//g' "./index.html"
          sed --in-place 's/url\: ".*"/url\: "v4\.json"/g' "./index.html"
      - name: Generate OpenAPI
        working-directory: ${{ env.TDPROTO_DIR }}
        run: |
          go run "./codegen/openapi/" > "${GITHUB_WORKSPACE}/${CLONE_DIR}/${OPENAPI_FILE}"
      - name: Commit and upload swagger
        working-directory: ${{ env.CLONE_DIR }}
        run: |
          git add --all
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git commit -m "Generate swagger on $(date)" --allow-empty
          git push
