---
name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Unit test environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Test codegen
        run: |
          go test ./codegen/...
